server:
  port: 7777

logging:
  level:
    org:
      springframework:
        boot: INFO
    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG

spring:
  profiles:
    active: file
  flyway:
    enabled: false
  security:
    user:
      name: piotr
      password: abc123

invoicing-system:
  allowedOrigins: http://localhost:4200,https://invocing-test-1.herokuapp.com
  csrf:
    disable: true
